### ISSUE TITLE
Error when compiling coffeescript

### ISSUE THREAD

**Issue by iosadchiy** [alg/hack_night#5]
When I go to /javascripts/dashboard.js I get the following:

```
throw Error("NoMethodError: undefined method `compile' for nil:NilClass\n  (in /home/ivan/p/hack_night/public/javascripts/dashboard.js.coffee)")
```

Have I missed some setup?

**Comment by iosadchiy** [comment]
OK, that was due to outdated packages in ubuntu repository.

But heroku is still affected

**Comment by iosadchiy** [comment]
What I don't like here is how the app starts to depend on something external that cannot be resolved by a simple `bundle install`

**Comment by iosadchiy** [comment]
I like this thing https://github.com/Sutto/barista
Doesn't support sprockets out of the box though (focuses on jammit)
Anyway, worth examining

**Comment by alg** [comment]
Didn't work this barista of your's. That's why I reverted to something more straightforward, and it never required anything but "bundle install" for me. So accusations are ungrounded. :)

**Comment by iosadchiy** [comment]
Ha! You do have node and coffee binaries installed on your system. Try removing them! ^_^
It's cool you've already looked into barista... at least the option is examined (and trashed :).

**Comment by alg** [comment]
You certainly can have a look if you like. I just couldn't make it work. As for the rest, what are our options? How's it supposed to work on Heroku at all, do you know?

**Comment by iosadchiy** [comment]
closing as resolved...

**Comment by joevandyk** [comment]
Getting this error too -- not sure where to start looking.

**Comment by iosadchiy** [comment]
Rails cannot find a javascript engine to compile coffeescript. Add therubyracer gem or install node.js and coffeescript binaries. Which js runtime will be used is determined by execjs gem (http://rubygems.org/gems/execjs) so you can probably start looking there

As for this issue, we ended up with therubyracer.
